const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const IC={home:'<path d="M3 11l9-8 9 8M5 10v10h5v-6h4v6h5V10"/>',compass:'<circle cx=12 cy=12 r=9 /><path d="M15.5 8.5l-2 5-5 2 2-5z"/>',chat:'<path d="M21 12a8 8 0 0 1-11.6 7.1L4 20l1-4.6A8 8 0 1 1 21 12z"/>',heart:'<path d="M12 20s-8-4.9-8-11a4.5 4.5 0 0 1 8-2.8A4.5 4.5 0 0 1 20 9c0 6.1-8 11-8 11z"/>',user:'<circle cx=12 cy=8 r=4 /><path d="M4 21a8 8 0 0 1 16 0"/>',sliders:'<path d="M4 7h9M19 7h1M4 17h1M11 17h9"/><circle cx=16 cy=7 r=2 /><circle cx=8 cy=17 r=2 />',plus:'<path d="M12 5v14M5 12h14"/>',search:'<circle cx=11 cy=11 r=7 /><path d="M20 20l-4-4"/>',send:'<path d="M21 3L10 14M21 3l-7 18-4-7-7-4z"/>',mic:'<rect x=9 y=3 width=6 height=11 rx=3 /><path d="M5 11a7 7 0 0 0 14 0M12 18v3"/>',photo:'<rect x=3 y=4 width=18 height=16 rx=3 /><circle cx=9 cy=10 r=1.5 /><path d="M21 16l-5-5-9 9"/>',smile:'<circle cx=12 cy=12 r=9 /><path d="M8 14a5 5 0 0 0 8 0M9 9.5h.01M15 9.5h.01"/>',sticker:'<path d="M5 4h14a1 1 0 0 1 1 1v9l-6 6H5a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1zM20 14h-5a1 1 0 0 0-1 1v5"/>',once:'<circle cx=12 cy=12 r=9 stroke-dasharray="3 3"/><path d="M10.5 9.5L12.5 8v8"/>',bookmark:'<path d="M6 3h12v18l-6-4-6 4z"/>',repeat:'<path d="M17 2l4 4-4 4M3 11V9a3 3 0 0 1 3-3h15M7 22l-4-4 4-4M21 13v2a3 3 0 0 1-3 3H3"/>',back:'<path d="M15 5l-7 7 7 7"/>',ban:'<circle cx=12 cy=12 r=9 /><path d="M5.6 5.6l12.8 12.8"/>',flag:'<path d="M5 21V4M5 4h11l-2 4 2 4H5"/>',trash:'<path d="M4 7h16M9 7V4h6v3M6 7l1 13h10l1-13"/>',x:'<path d="M6 6l12 12M18 6L6 18"/>',out:'<path d="M10 4H5v16h5M15 8l4 4-4 4M19 12H9"/>',mail:'<rect x=3 y=5 width=18 height=14 rx=3 /><path d="M3 7l9 6 9-6"/>',lock:'<rect x=5 y=11 width=14 height=10 rx=2 /><path d="M8 11V8a4 4 0 0 1 8 0v3"/>',at:'<circle cx=12 cy=12 r=4 /><path d="M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-4 8"/>',dots:'<path stroke-width=3 d="M5 12h.01M12 12h.01M19 12h.01"/>',check:'<path d="M5 12l5 5 9-10"/>',person:'<circle cx=12 cy=8 r=4 /><path d="M4 21a8 8 0 0 1 16 0"/>'};
document.body.insertAdjacentHTML('afterbegin','<svg width=0 height=0 style=position:absolute>'+Object.entries(IC).map(([k,v])=>`<symbol id=i-${k} viewBox="0 0 24 24">${v}</symbol>`).join('')+'</svg>');
const ic=(n,c='')=>`<svg class="ic ${c}"><use href="#i-${n}"/></svg>`;
const hue=s=>[...s].reduce((a,c)=>a+c.charCodeAt(0),0)%360;
const av=(x,z=46)=>{const h=hue(x.username||'a');return`<div class=av style="width:${z}px;height:${z}px;font-size:${z/2.3}px;background:${x.photo?`url(${x.photo}) center/cover`:`linear-gradient(135deg,hsl(${h} 90% 62%),hsl(${(h+40)%360} 90% 50%))`}">${x.photo?'':esc((x.name||x.username||'?')[0].toUpperCase())}</div>`};
const ago=t=>{if(!t||!t.toMillis)return'';const s=(Date.now()-t.toMillis())/1000;return s<60?"à l'instant":s<3600?(s/60|0)+' min':s<86400?(s/3600|0)+' h':(s/86400|0)+' j'};
function sheet(h){const o=document.createElement('div');o.className='ov';o.innerHTML=`<div class=sheet>${h}</div>`;o.onclick=e=>{if(e.target===o)o.remove()};document.body.append(o);return o}
let ME;const UC={};
const gu=async id=>UC[id]||(UC[id]={uid:id,...(await db.doc('users/'+id).get()).data()});
const byName=async n=>{const s=await db.doc('usernames/'+n).get();return s.exists?gu(s.data().uid):null};
const notify=(to,type,text)=>to==ME.uid?0:db.collection(`users/${to}/notifs`).add({type,from:ME.uid,fu:ME.username,text,seen:false,t:TS()});
async function follow(id){const a=db.doc(`users/${ME.uid}/following/${id}`),on=(await a.get()).exists,b=db.doc(`users/${id}/followers/${ME.uid}`);if(on){await a.delete();await b.delete()}else{await a.set({t:TS()});await b.set({t:TS()});await notify(id,'follow','a commencé à vous suivre')}return!on}
async function tog(k,id){const has=(ME[k]||[]).includes(id);await db.doc('users/'+ME.uid).update({[k]:has?FV.arrayRemove(id):FV.arrayUnion(id)});ME[k]=has?ME[k].filter(x=>x!=id):[...(ME[k]||[]),id];return!has}
function boot(page){return new Promise(r=>auth.onAuthStateChanged(async u=>{if(!u||!u.emailVerified){if(u)await auth.signOut();return location.href='login.html'}const d=await db.doc('users/'+u.uid).get();if(!d.exists)return auth.signOut();if(d.data().banned){await auth.signOut();document.body.innerHTML='<div style="min-height:100vh;display:grid;place-items:center;text-align:center;font-family:system-ui;padding:24px"><div><h1>Compte suspendu</h1><p style=margin:10px>Ton compte a été suspendu par l\'équipe Pebble.</p><a href=login.html>Retour</a></div></div>';return}ME={uid:u.uid,...d.data()};UC[u.uid]=ME;shell(page);r(ME)}))}
function shell(p){const N=[['index','home','Accueil'],['discover','compass','Découvrir'],['messages','chat','Messages'],['notifications','heart','Notifications'],['profile','user','Profil'],['settings','sliders','Paramètres']];
 document.body.insertAdjacentHTML('afterbegin','<nav><b>Pebble</b>'+N.map(n=>`<a href="${n[0]}.html" class="${n[0]==p?'on':''}">${ic(n[1])}<span>${n[2]}</span>${n[0]=='notifications'?'<span class=dot id=nb style=display:none></span>':''}</a>`).join('')+'</nav>');
 document.body.insertAdjacentHTML('beforeend','<footer>© 2026 Mourad Project · Pebble v1.2</footer>');$('main').after($('footer'));
 db.collection(`users/${ME.uid}/notifs`).where('seen','==',false).onSnapshot(s=>{const b=$('#nb');b.textContent=s.size;b.style.display=s.size?'inline-block':'none'});
 db.doc('config/announcement').onSnapshot(d=>{const n=d.data();$('#an')?.remove();if(n&&n.on&&n.text)document.body.insertAdjacentHTML('afterbegin',`<div id=an style="background:linear-gradient(135deg,#ffd43b,#ff9d00);color:#201a08;padding:8px 14px;text-align:center;font-weight:600;position:sticky;top:0;z-index:9">${esc(n.text)}</div>`)})}
async function openPost(p){const o=sheet(''),B=o.firstChild;B.classList.add('w');
 const paint=async()=>{const[a,cs]=await Promise.all([gu(p.uid),db.collection(`posts/${p.id}/comments`).orderBy('t').get()]),lk=(p.likes||[]).includes(ME.uid),sv=(ME.saved||[]).includes(p.id),rp=(ME.reposted||[]).includes(p.id);
  B.innerHTML=`<div class=row>${av(a,38)}<a class=sp href="profile.html?u=${a.username}"><b>${esc(a.username)}</b></a>${p.uid==ME.uid?`<button id=dl>${ic('trash')}</button>`:''}</div><img class=p src="${p.img}"><div class=acts><button id=lk class="${lk?'red':''}">${ic('heart',lk?'f':'')}</button><button id=rp class="${rp?'red':''}">${ic('repeat')}</button><span class=sp></span><button id=sv>${ic('bookmark',sv?'f':'')}</button></div><b>${(p.likes||[]).length} j'aime</b><p style="margin:6px 0"><b>${esc(a.username)}</b> ${esc(p.cap)}</p>${cs.docs.map(d=>{const c=d.data();return`<p class=mut><b style="color:var(--tx)">${esc(c.username)}</b> ${esc(c.text)}</p>`}).join('')}<div class=row style="margin-top:10px"><input class=in id=cm placeholder="Ajouter un commentaire…"><button class=btn id=cs>${ic('send')}</button></div>`;
  B.querySelector('#lk').onclick=async()=>{await db.doc('posts/'+p.id).update({likes:lk?FV.arrayRemove(ME.uid):FV.arrayUnion(ME.uid)});p.likes=lk?p.likes.filter(x=>x!=ME.uid):[...(p.likes||[]),ME.uid];if(!lk)notify(p.uid,'like','a aimé votre publication');paint()};
  B.querySelector('#rp').onclick=async()=>{await tog('reposted',p.id);paint()};B.querySelector('#sv').onclick=async()=>{await tog('saved',p.id);paint()};
  if(p.uid==ME.uid)B.querySelector('#dl').onclick=async()=>{await db.doc('posts/'+p.id).delete();o.remove()};
  B.querySelector('#cs').onclick=async()=>{const t=B.querySelector('#cm').value.trim();if(!t)return;await db.collection(`posts/${p.id}/comments`).add({uid:ME.uid,username:ME.username,text:t,t:TS()});notify(p.uid,'comment','a commenté : '+t.slice(0,60));paint()}};paint()}
function authPage(t,s,b,alt){document.body.innerHTML=`<div class=au><div class=hero><b style="font-size:28px">Pebble</b><div><h1>Partage.<br>Découvre.<br>Connecte-toi.</h1><p class=big style="margin-top:16px;font-size:18px;max-width:380px">Tes photos, tes amis et tes conversations, au même endroit.</p></div><small>© 2026 Mourad Project · Pebble v1.2</small></div><div class=form><div class=box><h2 style="font-size:32px">${t}</h2><p class=mut style="margin-bottom:8px">${s}</p>${b}<p class=mut style="text-align:center;margin-top:18px">${alt}</p></div></div></div>`}
const fld=(i,id,ph,ty='text')=>`<div class=fi>${ic(i)}<input class=in id=${id} type=${ty} placeholder="${ph}" autocapitalize=none></div>`;

async function withLoad(b,txt,fn,ms=2e4){const h=b.innerHTML;b.disabled=true;b.innerHTML='<span class=spin></span> '+txt;let to;try{return await Promise.race([fn(),new Promise((_,r)=>to=setTimeout(()=>r(Error("Délai dépassé : vérifie ta connexion, que Firestore Database est bien créée et que les règles sont publiées (voir README).")),ms))])}catch(x){const e=$('#er');if(e){e.className='err';e.textContent=x.message}}finally{clearTimeout(to);b.disabled=false;b.innerHTML=h}}
